### ISSUE TITLE
关于报错：ModuleNotFoundError: No module named 'apps'

### ISSUE THREAD

**Issue by Day333** [Joe-2002/sweettalk-django4.2#13]
我的环境
Django：4.2.6
Python：3.8
在按照说明进行环境配置和项目启动时，发现在pu3进行迁移时存在报错：
![pycharm64_l5xuUWLIwl](https://github.com/Joe-2002/sweettalk-django4.2/assets/109149132/7988d94d-bc85-457d-a599-20c2ea05734b)
经过检查后，发现了可能的原因，但由于项目文件docs中前后APP命名并不一致，这里我假设创建了名为“myProject”的项目和“myApp”的APP。
只需要将apps.py中的“apps.myapp”和setting.py中的列表INSTALLED_APPS中的“app.myapp”同时修改为“myapp”即可解决该问题。
如有不足，感谢您的指导！
望采纳问题！

**Comment by phoenix1337-personal** [comment]
同学你好！感谢提出问题，你的写法也是可以的。
  在Django的工程目录中，主 app 跟子 app 默认是保持同一级目录的关系的，这样的项目目录层次不是很清晰，当 app 或者其他项目相关的配置文件越来越多，非常不适合进行管理。我们把所有的apps归置在一个文件夹下（例如项目中的apps)是为了保证项目目录的整洁性和可读性。
