### ISSUE TITLE
插入数据报错"django.db.utils.IntegrityError: NOT NULL constraint failed: erp_test_goodscategory.name"

### ISSUE THREAD

**Issue by hu-qi** [Joe-2002/sweettalk-django4.2#15]
![image](https://github.com/Joe-2002/sweettalk-django4.2/assets/17986122/328ca5e1-bd14-469e-abd0-816986fa5119)

 这应该是新手最容易犯的错，经过群里大佬的指点和自己的摸索打印接受到的   `category_name`  发现我请求的数据格式不对。

![image](https://github.com/Joe-2002/sweettalk-django4.2/assets/17986122/9f7978d9-16c8-4965-a686-e1b91861f659)

因此，总结一下小白的报错解决方法：
- 1. 检查字段名称是否存在、字段类型是否符合预设
- 2. 检查请求数据格式是否符合预设
- 3. 断点调试或者输出关键节点信息进行问题定位及排查
- 4. 实在没法自行解决及时寻求外部协助

![image](https://github.com/Joe-2002/sweettalk-django4.2/assets/17986122/fab0ff47-caf6-4311-947e-4202672da327)

**Comment by phoenix1337-personal** [comment]
收到反馈：）
