### ISSUE TITLE
P03并没有提及到什么时候创建erp_test文件夹

### ISSUE THREAD

**Issue by INGg** [Joe-2002/sweettalk-django4.2#17]
P03并没有提及到什么时候创建erp_test文件夹；其实前面也没有提及到什么时候创建了apps文件夹；是不是要建立成apps/erp_test/data以及purchase呢

**Comment by INGg** [comment]
对应的data和purchase中的apps.py文件中的name字段是不是也要改成apps.erp_test.purchase呢嘤嘤嘤

**Comment by phoenix1337-personal** [comment]
同学你好，感谢提出问题。在Django的工程目录中，主 app 跟子 app 默认是保持同一级目录的关系的，这样的项目目录层次不是很清晰，当 app 或者其他项目相关的配置文件越来越多，非常不适合进行管理。我们把所有的apps归置在一个文件夹下（例如项目中的apps)是为了保证项目目录的整洁性和可读性。
apps.py文件中在应用名字前加入apps. 前缀即可完成注册。
