### ISSUE TITLE
P02 中创建项目与创建APP不连贯的错误

### ISSUE THREAD

**Issue by MoYanXG** [Joe-2002/sweettalk-django4.2#19]
创建项目的语句应该改为
django-admin startproject projectname .
在原语句后加英文点号
不添加这一步而进行创建App，会出现无法找到 manage.py 的错误

**Comment by Ethan-2004** [comment]
您好，首先非常感谢您的提出的 **issue**~
在这种情况下，当您遇到“无法找到 manage.py ”时，可能是因为当前工作目录并没有包含该文件。在使用您的方法 **django-admin startproject projectname .**  创建项目的时候，该命令会在当前目录下生成manage.py文件，所以可以直接创建app。建议您在含有manage.py文件的目录下执行 **python manage.py startapp appname** 命令，或者直接使用**django-admin startapp appname** 也是可以的，无需 manage.py 文件。
也欢迎您继续向我们提出您的宝贵建议，感谢~
